import Vue from 'vue';

import AccountIcon from 'vue-material-design-icons/Account';
import AccountCircleOutlineIcon from 'vue-material-design-icons/AccountCircleOutline';
import AccountOutlineIcon from 'vue-material-design-icons/AccountOutline';
import AccountMultipleIcon from 'vue-material-design-icons/AccountMultiple';
import BullseyeArrowIcon from 'vue-material-design-icons/BullseyeArrow';
import DatabaseImportIcon from 'vue-material-design-icons/DatabaseImport';
import DatabaseExportIcon from 'vue-material-design-icons/DatabaseExport';
import LabelIcon from 'vue-material-design-icons/Label';
import LabelOutlineIcon from 'vue-material-design-icons/LabelOutline';
import ImageMultipleIcon from 'vue-material-design-icons/ImageMultiple';
import ContentCopyIcon from 'vue-material-design-icons/ContentCopy';
import FormatListTextIcon from 'vue-material-design-icons/FormatListText';
import FormatListBulletedIcon from 'vue-material-design-icons/FormatListBulleted';
import EarthIcon from 'vue-material-design-icons/Earth';
import DeleteOutlineIcon from 'vue-material-design-icons/DeleteOutline';
import PlusIcon from 'vue-material-design-icons/Plus';
import PlusCircleIcon from 'vue-material-design-icons/PlusCircle';
import PencilOutlineIcon from 'vue-material-design-icons/PencilOutline';
import FileTableOutlineIcon from 'vue-material-design-icons/FileTableOutline';
import AnimationOutlineIcon from 'vue-material-design-icons/AnimationOutline';
import MagnifyIcon from 'vue-material-design-icons/Magnify';
import CheckOutlineIcon from 'vue-material-design-icons/CheckOutline';
import CheckCircleIcon from 'vue-material-design-icons/CheckCircle';
import CheckCircleOutlineIcon from 'vue-material-design-icons/CheckCircleOutline';
import AlertCircleOutlineIcon from 'vue-material-design-icons/AlertCircleOutline';
import CloseCircleOutlineIcon from 'vue-material-design-icons/CloseCircleOutline';
import LogoutVariantIcon from 'vue-material-design-icons/LogoutVariant';
import InformationOutlineIcon from 'vue-material-design-icons/InformationOutline';
import EmailOutlineIcon from 'vue-material-design-icons/EmailOutline';
import DotsVerticalCircleOutlineIcon from 'vue-material-design-icons/DotsVerticalCircleOutline';
import DotsVerticalIcon from 'vue-material-design-icons/DotsVertical';
import ContentSaveIcon from 'vue-material-design-icons/ContentSave';
import FilterOutlineIcon from 'vue-material-design-icons/FilterOutline';
import ChevronLeftIcon from 'vue-material-design-icons/ChevronLeft';
import ChevronRightIcon from 'vue-material-design-icons/ChevronRight';
import ChevronUpIcon from 'vue-material-design-icons/ChevronUp';
import ChevronDownIcon from 'vue-material-design-icons/ChevronDown';
import MenuDownIcon from 'vue-material-design-icons/MenuDown';
import TrashCanOutlineIcon from 'vue-material-design-icons/TrashCanOutline';
import WebhookIcon from 'vue-material-design-icons/Webhook';
import CodeBracesIcon from 'vue-material-design-icons/CodeBraces';
import CloseIcon from 'vue-material-design-icons/Close';
import VectorLinkIcon from 'vue-material-design-icons/VectorLink';
import VariableIcon from 'vue-material-design-icons/Variable';
import SendIcon from 'vue-material-design-icons/Send';
import SendClockIcon from 'vue-material-design-icons/SendClock';
import SendOutlineIcon from 'vue-material-design-icons/SendOutline';
import SendClockOutlineIcon from 'vue-material-design-icons/SendClockOutline';

import ReplyIcon from 'vue-material-design-icons/Reply';
import ReplyOutlineIcon from 'vue-material-design-icons/ReplyOutline';
import CardTextOutlineIcon from 'vue-material-design-icons/CardTextOutline';
import BellOutlineIcon from 'vue-material-design-icons/BellOutline';
import TargetIcon from 'vue-material-design-icons/Target';
import TagOutlineIcon from 'vue-material-design-icons/TagOutline';
import DomainIcon from 'vue-material-design-icons/Domain';
import ViewDashboardOutlineIcon from 'vue-material-design-icons/ViewDashboardOutline';
import SlackIcon from 'vue-material-design-icons/Slack';
import CellphoneIcon from 'vue-material-design-icons/Cellphone';
import FilePdfOutlineIcon from 'vue-material-design-icons/FilePdfOutline';
import BullhornOutlineIcon from 'vue-material-design-icons/BullhornOutline';
import HeadLightbulbOutlineIcon from 'vue-material-design-icons/HeadLightbulbOutline';
import TextBoxMultipleOutlineIcon from 'vue-material-design-icons/TextBoxMultipleOutline';
import OpenInNewIcon from 'vue-material-design-icons/OpenInNew';
import DragIcon from 'vue-material-design-icons/Drag';
import ContentSaveOutlineIcon from 'vue-material-design-icons/ContentSaveOutline';
import ShieldKeyOutlineIcon from 'vue-material-design-icons/ShieldKeyOutline';
import DownloadIcon from 'vue-material-design-icons/Download';
import ChartScatterPlotIcon from 'vue-material-design-icons/ChartScatterPlot';
import EmoticonWinkOutlineIcon from 'vue-material-design-icons/EmoticonWinkOutline';

import ClipboardTextOutlineIcon from 'vue-material-design-icons/ClipboardTextOutline';

Vue.component('plus-icon', PlusIcon);
Vue.component('pencil-outline-icon', PencilOutlineIcon);
Vue.component('logout-variant-icon', LogoutVariantIcon);
Vue.component('trash-can-outline-icon', TrashCanOutlineIcon);
Vue.component('close-icon', CloseIcon);
Vue.component('clipboard-text-outline-icon', ClipboardTextOutlineIcon);
